# Generated by Django 5.2.8 on 2025-11-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_unidad',
            field=models.CharField(choices=[('meses', 'Meses'), ('años', 'Años')], default='años', max_length=10),
        ),
        migrations.AddField(
            model_name='mascota',
            name='edad_valor',
            field=models.PositiveIntegerField(default=1, help_text='Edad numérica de la mascota'),
            preserve_default=False,
        ),
    ]
